### PR TITLE
add private key validation test

### PR DESCRIPTION
**Pull request by martgil**
This PR will add a private key validation test and update PgpKey class

close https://github.com/FlowCrypt/flowcrypt-ios/issues/1346 // if this PR closes an issue

issue #0000 // if it doesn't close the issue yet

Todo:
- [ ] validate private key in `readMany()` of pgp-keys.ts
- [ ] eliminate errors `TypeError { message: 'prvPacket.validate is not a function' }`
- [ ] complete the test for `unencrypted private key`, `encrypted private key` validation.  

reference: https://github.com/FlowCrypt/flowcrypt-browser/pull/4271

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests will be added later (issue #...)
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
@IvanPizhenko sorry for any disturbance, sir. I would like to ask for any hints?

I'm trying to achieve the same way that sir, Roman did on `FlowCrypt/flowcrypt-browser#4271` when validating the key. 
I keep getting the error of `prvPacket.validate is not a function` even though I've added the `.validate(): Promise<any>;` on `openpgp.d.ts` type definition file. I feel like I'm still missing something but not sure exactly what it is.

I also tried to find any references for the `.validate()` but I only get results from the `openpgp.d.ts` and `openpgp-keys.ts(browser extension) / pgpkey.ts(ios-repo)`

Any feedback would be much appreciated 🙇🏻‍♂️ Thanks!

**Comment by IvanPizhenko** [comment]
@martgil `.d.ts` file is just type definitions for the Typescript compiler, it does not provide function implementation. I think browser extension may use modified version of openpgp.js with such custom function added. You better ask Roman about this.

**Comment by tomholub** [comment]
Likely, flowcrypt-ios uses an older version of OpenPGP.js than browser extension does.

@IvanPizhenko we could update the iOS OpenPGP.js to v5 (instead of FES, initially), what do you think? It won't be an easy task.

**Comment by IvanPizhenko** [comment]
@tomholub yes, we can try to do it.

**Pull request closed without merging**
