### PR TITLE
#2269 Added prettier

### LINKED ISSUE #2269: Implement Prettier
Implement a prettier feature (like Flowcrypt browser extension) in `appium` and `core`.
Also, turn the autoSave setting to true, so that TypeScript code will be auto-formatted.

@sosnovsky What do you think?

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR added prettier

close #2269 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by sosnovsky — COMMENTED** [review]
Looks good, but let's also update compiled Core js file in app bundle, to check if everything works well.

It's done by running `npm run build` in `/Core` directory.

**Comment by ioanmo226** [comment]
Sounds good!

**Review by sosnovsky — COMMENTED** [review]
I missed it on the first review, but let's update `.prettierignore` to also include:
- `Core/build/` - no need to prettify built files
- `Core/source/lib` - these are 3rd-party libs, so let's leave their original code

And `Core/.jsbeautifyrc` file isn't needed anymore

**Comment by ioanmo226** [comment]
I think there is no need to include `Core/build/` in the `.prettierignore` file because the `build` directory is already specified in the `.gitignore` file within the `Core` folder. Additionally, `prettier` prioritizes the rules specified in `.gitignore` before considering `.prettierignore`.

**Comment by sosnovsky** [comment]
> I think there is no need to include `Core/build/` in the `.prettierignore` file because the `build` directory is already specified in the `.gitignore` file within the `Core` folder. Additionally, `prettier` prioritizes the rules specified in `.gitignore` before considering `.prettierignore`.

Sounds good 👍

**Review by sosnovsky — COMMENTED** [review]
All good now, just need to copy `Core/lib` files from `master`, as here they were formatted without updated `.prettierignore`

**Review by sosnovsky — APPROVED** [review]
👍

**Pull request merged**
