### PR TITLE
Update npm packages within known vulnerabilities

### LINKED ISSUE #1535: reported vulnerabilities in npm packages
image

Edited by mart:
Additionally, I should have to break this task into smaller chunks as (1) I need to update webpack 5 on `/Core` path (2) I'm having difficulties on updating of most vulnerable npm packages on the `/appium` path but I'm still into it.

- [x] #1580
- [x] #1597 (may need to wait for appium 2.0 non-beta version)

### PR DESCRIPTION
**Pull request by martgil**
This PR will update npm dev dependencies with known vulnerabilities.

To verify the changes:
1. npm i
2. npm audit
Screen Shot 2022-05-11 at 2 01 33 PM

close #1535  // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)
- Difficult to test (explain why)
- Not worth testing
- Tests will be added later (issue #...)
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
sir @tomholub  - I believe in order to completely eliminate vulns in appium package we need to migrate to appium 2.0 ( beta version). 

I did have a little progress on this issue,  like using a prefix 'appium:<capabilityName>' to follow appium 2.0 needs  which indeed surpass the previous error. [ref](https://www.headspin.io/blog/migrating-to-appium-2-0-part-1-capability-prefixes)

I'm getting a new error that states:
> Could not find a driver for automationName 'XCUITest' and platformName iOS'. Have you installed a driver that supports those capabilities?

I execute `appium driver list --installed` as suggested but have no driver found.

Although, I have some clue that I might need to find a new driver but have no idea which/how to proceed further - do you have any hint about it?

I have found https://github.com/appium-boneyard/appium-ios-driver which might be helpful.

**Comment by martgil** [comment]
I understand sir.

> Although, using the beta version may bring some issues as well. Do you know when they expect to release non-beta 2.0?

It seems the expected release date for non beta 2.0 isn't announced anywhere just yet as the beta version is continuously being developed.

**Comment by tomholub** [comment]
Maybe we should wait a bit longer. Once 2.0 is available, that would be the time to update.

**Comment by martgil** [comment]
Ok sir, Tom. I will leave this PR open so we can get back to it anytime after the appium 2.0 is available.

**Comment by tomholub** [comment]
It may take a long time - I'll close it and we can reopen at that point.

**Pull request closed without merging**
