### PR TITLE
#1702 Use prebuilt texture dependency

### LINKED ISSUE #1702: speed up project build in ci with prebuilt dependency - Texture
It take 28 minutes to build the project, and I seem to recall that Texture took a good chunk of that. Is that true? If yes, could the build times be sped up by making a prebuilt swift package?

image

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR uses prebuilt texture dependency to speedup ci build

close #1702 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@sosnovsky As I checked with this prebuilt Texture framework, CI speed is about 2 mins faster(still build fails though. only unit tests pass)
Do you think it's worth we still go forward and fix? 
FYI I used [pod builder](https://github.com/Subito-it/PodBuilder) library and it has few maintainers.

**Comment by sosnovsky** [comment]
@ioanmo226 I think we should check how much time takes building of each pod (with tool like https://github.com/MobileNativeFoundation/XCLogParser) to see if precompiling `Texture` will have a big effect on total build time.

Maybe it's possible to manually compile `Texture.xcframework` (without using additional gem like `podbuilder`) or add support for SPM (here is fork of original `Texture` with added SPM support)?

**Comment by sosnovsky** [comment]
@ioanmo226 it looks like `Texture` won't have any new releases in the nearest future, as there is no new commits since December. So for now it'll be okay just manually compile `xcframework` without adding new libraries.

Maybe in the future we'll switch to SwiftUI and will be able to completely remove `Texture` - https://github.com/FlowCrypt/flowcrypt-ios/issues/782

**Comment by ioanmo226** [comment]
Sounds good

**Comment by sosnovsky** [comment]
@ioanmo226 I missed this link in my first comment - https://github.com/shimastripe/Texture/releases/tag/3.1.1 (it's a fork with SPM support)

**Comment by ioanmo226** [comment]
Which way do you prefer(SPM vs manually compile framework file)?
I think manually compiling framework would be fine as we would move to `SwiftUI` soon.

**Comment by sosnovsky** [comment]
@ioanmo226 I prefer SPM as including full `xcframework` will make `FlowCrypt` repository size much bigger.

It'll be better to create our own fork with SPM support (as for [mailcore](https://github.com/FlowCrypt/mailcore2) and [GMP](https://github.com/FlowCrypt/GMP)). @tomholub will need to create new repository (https://github.com/FlowCrypt/Texture), when he'll be available

**Pull request closed without merging**
