### PR TITLE
added test for reply email

### LINKED ISSUE #937: ui test for tapping the reply icon
This is asking for a UI test as well as follows:

1) open any conversation
2) tap the reply icon
3) verify that you are on reply screen, and verify the information that was prefilled:
   - to: (contain email address of the person who sent the message you were viewing earlier)
   - quoted message content

will file another issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/936#issuecomment-962208121_

### PR DESCRIPTION
**Pull request by fcvakintos**
This PR contains test for checking reply email
close #937 

----------------------------------

**Tests** 
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
@fcvakintos thank you - which IDE do you use for editting? I suppose vscode? I have added a workspace file https://github.com/FlowCrypt/flowcrypt-ios/blob/master/flowcrypt-ios.code-workspace - if you open it from there, the IDE should use consistent settings between my and your edits (eg tab size of 2).

Also, the IDE will suggest a linting plugin for you to catch missing awaits.

**Comment by tomholub** [comment]
There is also autoformat on save enabled. With that, if you go to each of the files in https://github.com/FlowCrypt/flowcrypt-ios/pull/1016/files and hit CTRL+S, and then commit that here, the diff in this PR should be much smaller (~ 5 files).

**Comment by fcvakintos** [comment]
I use WebStorm

**Comment by tomholub** [comment]
I see. If you'll continue using WebStorm, please set indent of two spaces, so that it wouldn't collide with my settings. Then have it reformat the project.

**Comment by fcvakintos** [comment]
@tomholub pushed fixes

**Review by tomholub — APPROVED** [review]

**Pull request merged**
