### PR TITLE
Add script for automatic generating all the icons

### LINKED ISSUE #734: check sharpness of app icons
This fixes the issue although it makes the icons all somewhat unsharp - I think it has something to do with how the pngs were generated or handled (maybe they were not produced from a vector but by down-scaling another png?). 

I'll merge it for now but will have someone later have a look to make sure the icons have crisper edges.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/731#pullrequestreview-787208481_

### PR DESCRIPTION
**Pull request by limonte**
This PR adds a script that automatically generates all icons. 

Under the hood, it uses `rsvg-convert` which is available for Ubuntu (`sudo apt-get install librsvg2-bin`) as well as for macOS (`brew install librsvg`). 

I also tested [`ImageMagick`](https://github.com/ImageMagick/ImageMagick), [`svgexport`](https://github.com/shakiba/svgexport), [`sharp`](https://github.com/lovell/sharp) and `rsvg-convert` produces the best results.

AFAIK this is the best sharpness that could be achieved with automatic scaling. 

Close #734

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by limonte** [comment]
SVG icons are taken from https://github.com/FlowCrypt/flowcrypt-design/pull/22 and are currently placed in the `Scripts` folder which I believe is the wrong place for them.

Please suggest the right place for SVG icons, thank you!

**Review by tomholub — APPROVED** [review]
Thanks!

**Comment by tomholub** [comment]
you can add the svgs into a new folder `asset-sources/icons`

**Comment by limonte** [comment]
> you can add the svgs into a new folder `asset-sources/icons`

Done 👍

**Review by tomholub — APPROVED** [review]
Thanks!

**Pull request merged**
