### PR TITLE
#1575 Automatic submit on passphrase paste

### LINKED ISSUE #1575: choosing pass phrase from ios password manager to trigger dialog confirmation
I enter my pass phrase from native ios password manager

At the moment, when I choose the pass phrase and it gets copied into the dialog, I still have to tap "confirm".

It would be better if choosing key from the password manager automatically triggered confirmation in these situations. Applies to:

- [x] setup with backup from inbox: enter pass phrase for backup emails (non-enterprise)
- [x] setup - create a new key (non-enterprise)
- [x] setup - confirm pass phrase for new key (non-enterprise)
- [x] setup with ekm: create pass phrase
- [x] setup with ekm: confirm pass phrase
- [x] read email: enter pass phrase
- [x] send email: enter pass phrase
- [x] refresh ekm keys: enter pass phrase

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR adds automatic passphrase submit when it was pasted into textfield.

close #1575

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@sosnovsky FYI I just merged latest master changes to this PR

**Comment by tomholub** [comment]
I didn't know it would be such a big task - expected it to be easier than that 👀

**Comment by sosnovsky** [comment]
> I didn't know it would be such a big task - expected it to be easier than that 👀

Yeah, initially I thought too, but it required changes of handling input in several different places and also in modals.
I created separate delegate and textfield action for handling string paste, so now we can easily integrate this functionality in any textfield.

**Review by ioanmo226 — APPROVED** [review]
Looks good 👍

**Pull request merged**
