### PR TITLE
Add accessibility ids to menu and pub key

### LINKED ISSUE #1187: menu bar items accessibility ids
@Kharchevskyi @tomholub I found new issue after this fix, now we dont have accesibility id for menu bar items
it is after this fix i think, because now accessibility id = "INBOX" is not unique
Screenshot 2021-12-07 at 10 26 21

can we add accessibility id for menu bar items?
something like this - menubarIteminbox, menubaritemchat and etc

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/1127#issuecomment-987685871_

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR adds accessibility ids to menu and pub key

close #1187 #1068 
----------------------------------

**Tests**:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by tomholub — DISMISSED** [review]
These look good to me. @fcvakintos let us know if this works for you.

**Comment by fcvakintos** [comment]
@tomholub checking
will update the tests

**Comment by fcvakintos** [comment]
@tomholub pushed fix for autotests

**Review by tomholub — APPROVED** [review]
much better

**Pull request merged**
