### PR TITLE
#1852 Appium tests fix

### LINKED ISSUE #1852: Fix ui test in semaphoreci
Sometimes ui tests fail in SemaphoreCI with below errors. (I think these errors didn't happen before we upgrade appium to 2.0 beta)

https://flowcrypt.semaphoreci.com/workflows/9d9a7dd9-b4ff-4ebd-8c5f-a7faf991faed/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5&suite_id=45841c8d-bf0e-3ac4-bd31-bea52c1da781&test_id=bfbc6f8d-98ab-3adb-823d-0262084f8f63
https://flowcrypt.semaphoreci.com/jobs/31010aff-e047-492d-bfc7-a346a8d92160/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5

```
Error: Element isn't visible after 15000 seconds. Error: Error: element ("~aid-navigation-item-inbox") still not displayed after 15000ms
    at Function.ElementHelper.waitElementVisible (/Users/semaphore/git/flowcrypt-ios/appium/tests/helpers/ElementHelper.ts:16:13)
    at async MailFolderScreen.checkInboxScreen (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/mail-folder.screen.ts:129:5)
    at async /Users/semaphore/git/flowcrypt-ios/appium/tests/specs/mock/inbox/CheckAllEmailSignatureCases.spec.ts:30:7
    at async MockApi.withMockedApis (/Users/semaphore/git/flowcrypt-ios/appium/api-mocks/mock.ts:100:7)
    at async UserContext.<anonymous> (/Users/semaphore/git/flowcrypt-ios/appium/tests/specs/mock/inbox/CheckAllEmailSignatureCases.spec.ts:27:5)

```

```
Error: Element isn't visible after 15000 seconds. Error: Error: element ("~aid-menu-btn") still not displayed after 15000ms
    at Function.ElementHelper.waitElementVisible (/Users/semaphore/git/flowcrypt-ios/appium/tests/helpers/ElementHelper.ts:16:13)
    at async Function.ElementHelper.waitAndClick (/Users/semaphore/git/flowcrypt-ios/appium/tests/helpers/ElementHelper.ts:53:5)
    at async MenuBarScreen.clickMenuBtn (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/menu-bar.screen.ts:54:5)
    at async KeysScreen.openScreenFromSideMenu (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/keys.screen.ts:118:5)
    at async /Users/semaphore/git/flowcrypt-ios/appium/tests/specs/mock/setup/CheckDecryptMessageWhenNoKeys.spec.ts:33:7
    at async MockApi.withMockedApis (/Users/semaphore/git/flowcrypt-ios/appium/api-mocks/mock.ts:100:7)
    at async UserContext.<anonymous> (/Users/semaphore/git/flowcrypt-ios/appium/tests/specs/mock/setup/CheckDecryptMessageWhenNoKeys.spec.ts:29:5)

```

Also need to update this as we get below error.
`- artifact push job ~/Library/Logs/DiagnosticReports/FlowCrypt_*`

> [Oct  4 19:20:59.057] Error pushing artifact: path '/Users/semaphore/Library/Logs/DiagnosticReports/FlowCrypt_*' does not exist locally

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR tries to fix failing appium tests on Semaphore

close #1852

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
Let me run this test 2-3 times on Semaphoreci and see if passes everytime.

**Comment by sosnovsky** [comment]
Seems like test fails are quite random, I'll continue investigating

**Comment by sosnovsky** [comment]
@ioanmo226 I think I've found what caused tests fails - `webdriveragent` building takes longer time than in previous appium version, so I increased `connectionRetryTimeout` config value and tests work well now.

**Comment by ioanmo226** [comment]
Looks good.
Nice catch 👍

**Review by ioanmo226 — APPROVED** [review]

**Pull request merged**
