### PR TITLE
Missing orientations for iPad

### LINKED ISSUE #724: missing orientations for iPad, missing icons?
image

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #724

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ivan-ushakov** [comment]
Icons are fine.

**Comment by tomholub** [comment]
@ivan-ushakov please focus on 0.6.0 issues before doing 0.7.0. Always issues with lower version number first.

**Comment by ivan-ushakov** [comment]
This one was in "Priorities iOS" list.

**Comment by tomholub** [comment]
Got it. Indeed, you're not wrong :-)

**Comment by tomholub** [comment]
And it is important, no doubt. Thanks

**Pull request merged**
