### PR TITLE
#1471 Improve recipient popup and UI testing

### LINKED ISSUE #1471: improving tests for recipient popup
_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1464#pullrequestreview-930831990_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR improved recipient popup and UI testing.

close #1471 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by tomholub — APPROVED** [review]

**Comment by ioanmo226** [comment]
@tomholub I can see that 0.9.0 milestone is closed.
I think this issue should be included in 0.9.0 milestone (This PR also includes small popup fix). at least 0.91 milestone.

**Comment by tomholub** [comment]
No prob - I'll wait with the release until this merges

**Comment by ioanmo226** [comment]
> `[Update Semaphore configuration](/FlowCrypt/flowcrypt-ios/pull/1483/commits/f58aa8431da2b7f7221494809bb492c831d0fc43) `

OK. let me try his approach

**Comment by ioanmo226** [comment]
@tomholub Please review

**Review by tomholub — APPROVED** [review]

**Comment by ioanmo226** [comment]
@tomholub Please review again. Previous ios version was incorrect

**Review by tomholub — APPROVED** [review]

**Pull request merged**
