### PR TITLE
#1588 Rename PassPhraseService

### LINKED ISSUE #1588: PassPhraseService, PassPhraseServiceType, passPhraseService to be called `CombinedPassPhraseStorage`
since it combines two types of pass phrase storages

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR renamed PassPhraseService.

close #1588 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by sosnovsky — DISMISSED** [review]

**Comment by ioanmo226** [comment]
@sosnovsky, @tomholub  As you might noticed, `CheckReplyMessageWithChangingRecipient` ui tests fail on semaphoreci (i tested on local and it fails too)
I debugged it and found that it's because my name (Ioan at Flowcrypt) `at` was when displaying name as `at` is declared `middle name` (When using google contacts query to get contact info and display it in recipient list)
So I suggest to use displayName if it's not nil and empty. 
If not, then use givenName + middleName + familyName

Let me know what you think.

```
[iPhone 13 iOS 15.4 #0-16] » /tests/specs/live/inbox/CheckReplyMessageWithChangingRecipient.spec.ts42:41
[iPhone 13 iOS 15.4 #0-16] INBOX: 42:41
[iPhone 13 iOS 15.4 #0-16]    ✖ test for replying to my own email and changing recipient42:41
[iPhone 13 iOS 15.4 #0-16]42:41
[iPhone 13 iOS 15.4 #0-16] 1 failing (1m 34.8s)42:41
[iPhone 13 iOS 15.4 #0-16]42:41
[iPhone 13 iOS 15.4 #0-16] 1) INBOX:  test for replying to my own email and changing recipient42:41
[iPhone 13 iOS 15.4 #0-16] Error: expected text within 15000ms to be "  Ioan at FlowCrypt  " but got last value "  Ioan FlowCrypt  "42:41
```

image

**Comment by tomholub** [comment]
`displayName` is definitely better than creating our own.

**Comment by ioanmo226** [comment]
what if displayName is nil or empty?

**Comment by tomholub** [comment]
In that case the others are likely also nil or empty. I would just use it as it comes: nil is nil, empty is empty, proper value is proper value.

**Review by sosnovsky — APPROVED** [review]

**Pull request merged**
