### PR TITLE
[waiting for impl] issue #691 ui tests for saving drafts

### LINKED ISSUE #691: ui tests for saving drafts
>     Difficult to test (explain why). there was not tests to this modules ( gmail service etc ). if we need to cover it with tests I would prefer it as separate issue.

This should be covered by ui tests, I'll file an issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/690#issuecomment-945174146_

### PR DESCRIPTION
**Pull request by fcvakintos**
This PR covers issue #691
close #691

issue #873

**Tests** 
- Tests will be added later (issue #873 )

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by fcvakintos** [comment]
@tomholub do not merge till we will get fix for issue

**Comment by tomholub** [comment]
> @tomholub do not merge till we will get fix for issue

In these situations best to mark the PR as a draft:

image

**Comment by tomholub** [comment]
@fcvakintos you should convert this to draft to indicate it's waiting for merging. Also, use a more descriptive title to say what is being tested.

**Comment by tomholub** [comment]
I've disabled drafts for the time being, so unfortunately this PR may need to wait a while :-( sorry.

**Comment by fcvakintos** [comment]
@tomholub  ok, thanks

**Comment by tomholub** [comment]
I'll have to close this. Once drafts are closer to implementation, you can use the branch for inspiration, or re-open.

**Pull request closed without merging**
