### PR TITLE
Added log out to menu and to recovery controler

### PR DESCRIPTION
**Pull request by Kharchevskyi**
https://github.com/FlowCrypt/flowcrypt-ios/issues/73

Simulator Screen Shot - iPhone 6 - 2019-09-13 at 19 28 57

Added: 
- log out and settings to menu
- log out on recovery 
- Menu UI in code

### CODE REVIEW

**Comment by tomholub** [comment]
Thanks for the screen shot! Both `Settings` and  `Log out` are slightly off vertically. I'll demonstrate

**Comment by tomholub** [comment]
image

The green lines should be of equal length but they are not
1) the icons appear to be of different size
2) the text is vertically misaligned from the center of each icon

Sorry, I do this to everybody. I can't stand visual misalignment.

**Comment by Kharchevskyi** [comment]
Yeap, missed up. Fixed text alignment. 
But icons have the same size 24*24. Maybe there is simulator issues. Have you tried on a device? 
Screen Shot 2019-09-13 at 21 50 14
Screen Shot 2019-09-13 at 21 50 26

**Comment by tomholub** [comment]
Yeah I figured they have the same size technically, but visually one looks larger because it's a square, and one looks smaller due to being a circle (with a bit of padding). They have different "visual weight".

But it's not the worst, I'll address it some other day.

**Pull request merged**
