### PR TITLE
#1568 Remove test-specific delay from prod code

### LINKED ISSUE #1568: avoid test-specific delays in prod code
There must be a more reasonable way to fix the issue. It could be a change to test code or production code (maybe the flow would have to be changed to be easier to test, idk).

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1510#discussion_r864162554_

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR removes test-specific delay from prod code.

close #1568

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by tomholub — APPROVED** [review]

**Comment by ioanmo226** [comment]
Let me run UI test one more time in semaphoreci. To me It seems like this issues happens sometimes.

**Comment by ioanmo226** [comment]
@sosnovsky As I thought, this issue still happens. Please check and fix

**Comment by sosnovsky** [comment]
> @sosnovsky As I thought, this issue still happens. Please check and fix

Re-checking it

**Comment by sosnovsky** [comment]
@ioanmo226 I tried to run tests a couple times on semaphore - they passed well, seems like issue is fixed now.
I added timeout before app restarting, maybe on semaphore app termination took more time and lead to crashes.

**Review by tomholub — APPROVED** [review]

**Comment by ioanmo226** [comment]
@sosnovsky This issue happened again on master.

**Comment by ioanmo226** [comment]
ok

**Pull request merged**
