### PR TITLE
Fixed side menu bug

### PR DESCRIPTION
**Pull request by RomanKovalchuk2019**

### CODE REVIEW

**Comment by tomholub** [comment]
addresses #24

**Comment by RomanKovalchuk2019** [comment]
You would merge all changes to master branch by yourself?

**Comment by tomholub** [comment]
Correct. I want to control what goes onto master, at least initially. If you end up joining us, then over time you could possibly merge them yourself, depending on the character of the issue (security related PRs should always receive my review).

**Comment by RomanKovalchuk2019** [comment]
Ok, thanks for answering

**Pull request merged**
