### PR TITLE
issue 1019 show alert on bad backup pp

### LINKED ISSUE #1019: entering wrong pass phrase when recovering from inbox backup should show modal
1) log into a regualar gmail account (non-enterprise) that has backups in inbox
2) give it wrong pass phrase

expected: modal

actual: view disappears, enters main flow

### PR DESCRIPTION
**Pull request by tomholub**
This PR ensures that bad pass phrases are handled well when recovering from inbox backups.

close #1019

----------------------------------

**Tests**:
- ui tests will be added later - will file issue shortly

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
UI test should be written for this:
1) log into an account that is not on enterprise domain, that has backups in inbox
2) enter a wrong pass phrase during setup, click continue
3) you should be seeing a modal telling you the pass phrase is wrong. Click ok
4) you should stay on the same screen
5) enter correct pass phrase, click continue
6) you should be seeing the inbox
7) open one encrypted email, make sure it opens successfully

**Comment by tomholub** [comment]
@sosnovsky could you please help - why is it complaining about ui on non-main thread when I added MainActor on all the methods? Reproduce with the steps above.

image

**Comment by sosnovsky** [comment]
When trying to find fix for this issue I came across 2 useful flags for Swift concurrency - `-Xfrontend -warn-concurrency -Xfrontend -enable-actor-data-race-checks` (https://twitter.com/olebegemann/status/1421144304127463427)
These flags add additional code checks, which are not enabled by default, and they found 55 errors in our current code.

**Comment by tomholub** [comment]
very useful

**Comment by sosnovsky** [comment]
@tomholub I pushed commit with fix for `non-main thread` issue - it seems in some cases code which isn't inside `Task` runs on non-main thread even with `@MainActor`.

**Comment by tomholub** [comment]
> @tomholub I pushed commit with fix for `non-main thread` issue - it seems in some cases code which isn't inside `Task` runs on non-main thread even with `@MainActor`.

Ah - that means, MainActor has no effect if code was not run from a Task directly. That makes sense.

**Comment by tomholub** [comment]
Looking at your code changes - looks good. That means, once we do #997 everywhere, the code should behave in a more predictable manner.

**Comment by tomholub** [comment]
The PR is then ready for review 👍

**Review by sosnovsky — APPROVED** [review]

**Pull request merged**
