### PR TITLE
#2614 fix: decryption error for message sent via encrypted contact page

### LINKED ISSUE #2614: Decryption error for message sent via Encrypted Contact Page
Descrption:

Encrypted messages sent with attachment via [FlowCrypt's Encrypted Contact Page ](https://flowcrypt.com/docs/getting-started/send-and-receive/encrypted-contact-page.html) cannot be decrypted correctly. The JSON object were rendered into the message view instead of decrypting and rendering the decrypted message and its attachment.

Screenshot:

image

Reference:

https://mail.google.com/mail/u/human@flowcrypt.com/#archive/FMfcgzQVxtmgFdMvXxLQkxdRzcFvXtlh

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed decryption error for message sent via encrypted contact page

close #2614 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@martgil I'm attempting to send an encrypted message via the encrypted contact page to `e2e.enterprise.test@flowcrypt.com` for a UI test, but it's throwing the following error. 

Could you check the error log and let me know what's causing this? This issue is currently blocking me from implementing the UI test for this fix. 

image

**Comment by martgil** [comment]
Hi @ioanmo226 could be because of expired key most probably.

To verify this claim of mine, please kindly run this public key to the flowcrypt browser extension's compatibility checker: https://flowcrypt.com/pub/e2e.enterprise.test@flowcrypt.com?show=pubkey

The openpgp compatibility checker is in the advanced settings of FlowCrypt settings > experimental.

Observe if the keys are expired (most probably).

Once confirmed, please extend the keys expiration and submit the updated keys to https://flowcrypt.com/attester/update-public-keys

I have the PR on flowcrypt-web for fixing the missing error message details for expired keys and is already under review by Roma.

Hope this helps.

**Comment by ioanmo226** [comment]
Hmmmm... Just checked but I think it's not expired yet?
image

**Comment by martgil** [comment]
The issue looks like something else. Unfortunately, I dont have access to my computer right now to check the issue but can check it tomorrow if its okay?

**Comment by ioanmo226** [comment]
No problem at all. I can work on other issue.

**Comment by martgil** [comment]
Got it - thanks!

**Comment by sosnovsky** [comment]
Hi @ioanmo226, mentioned error happens because our config doesn't allow senders from `flowcrypt.com` domain:

Screenshot 2024-10-28 at 23 13 44

To send encrypted message you should just change email address to non-flowcrypt domain.

**Comment by ioanmo226** [comment]
Aha, I see. Thank for checking it.

**Comment by ioanmo226** [comment]
However I think we should display actual error message response.error.message (Senders on flowcrypt.com domain not allowed) instead of "Server says this was a bad request" generic error message

**Comment by martgil** [comment]
Hi @ioanmo226 - yes, I will include this case to my PR right now: https://github.com/FlowCrypt/flowcrypt-web/pull/1856

**Comment by martgil** [comment]
I'm done at adding some error handling for the reported issue; Already included in https://github.com/FlowCrypt/flowcrypt-web/pull/1856.

**Review by sosnovsky — APPROVED** [review]
Works well 👍

**Pull request merged**
