### PR TITLE
Feature/issue 529 update pods

### LINKED ISSUE #285: support building / running on M1
@seisvelas @tomholub is it possible to merge this PR with updated Readme and Realm and create a new issue for updating project with M1 support?

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/issues/281#issuecomment-816901817_

### LINKED ISSUE #302: mailcore2-ios http
@tomholub please take a look 

From `pod instal` logs
```
'mailcore2-ios' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.
```

### LINKED ISSUE #529: update cocoapods libraries to the latest versions
Currently app uses many outdated libraries, we should update them to the latest versions as they possibly include some fixes and performance improvements

Screenshot 2021-09-24 at 12 05 57

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR includes:
- all pods and gems updated to the latest versions
- use Swift Package Manager for `mailcore2` library (Cocoapods version doesn't work on M1 Macs)
- building and running tests fixed for M1 Macs
- `swiftformat` is used from embedded pod (instead of system one). This change is recommended in `swiftformat` repository - https://github.com/nicklockwood/SwiftFormat#alternative-locally-installed-swiftformat, as previous config could lead to inconsistencies in formatting for different team members (initially `swiftformat` failed to run for me, possibly because I'm using zsh instead of bash and Xcode failed to find system `swiftformat`)

close #529
close #285 // edited tom - this also fixed this issue
close #302 // edited tom - also this

----------------------------------

**Tests**:
- I ran unit_tests - all tests passed
- wasn't able to run UI tests as I need `flowcrypt-ios/FlowCryptUITests/test-ci-secrets.json` file

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Could you have a look at the CI tests - can you access them? https://flowcrypt.semaphoreci.com/workflows/90cb5578-60f3-4714-ba4f-11a037d5eae9?pipeline_id=72763e1f-a583-4292-a1e3-01f84c9f4302

**Comment by sosnovsky** [comment]
@tomholub no, I get 404 error there

**Comment by tomholub** [comment]
Try again now - sent invite (you may need to log in with GitHub)

**Comment by sosnovsky** [comment]
Yes, now I can see them, checking, thanks!

**Review by tomholub — APPROVED** [review]
Changes all look good.

It seems maybe you also fixed https://github.com/FlowCrypt/flowcrypt-ios/issues/302 as a side effect? Since we are checking a particular commit from master now, where the http issue was supposed to be fixed?

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
>  Your Ruby version is 2.5.1, but your Gemfile specified 3.0.2 00:06 

Semaphore has a command for this, something like `sem-version ruby 3.0.2` could do. So you don't have to manually change the ruby version on the machine.

**Comment by tomholub** [comment]
docs https://docs.semaphoreci.com/programming-languages/ruby/#supported-ruby-versions

**Comment by sosnovsky** [comment]
Yes, `http` issue should be fixed too ✅

I checked Semaphore documentation - for macOS images they have only ruby 2.3.7 and 2.5.1 preinstalled (https://docs.semaphoreci.com/ci-cd-environment/macos-xcode-11-image/#ruby), so I changed ruby version back to 2.5.1 and installed previous Cocoapods version which supports ruby 2.5

**Review by tomholub — APPROVED** [review]

**Pull request merged**
