### PR TITLE
There are swift files which are not part of the project

### LINKED ISSUE #990: there are swift files which are not part of the project
I just deleted some in #404 - what is the way to find the rest?

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #990

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ivan-ushakov** [comment]
Removed:

1. `FlowCrypt/Functionality/Error Handling/GmailServiceErrorHandler.swift`
2. `FlowCryptCommon/Throttler.swift`
3. `FlowCryptUI/Cell Nodes/MessageSenderNode.swift`

**Review by tomholub — APPROVED** [review]

**Comment by ivan-ushakov** [comment]
I decided to go with [this script]( https://github.com/PaulTaykalo/swift-scripts ) as @Kharchevskyi  suggested and found only three files above.

**Comment by Kharchevskyi** [comment]
what about unused code? 
```
Item< func performSomeNewSchema [private] from: FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift:150:0>
Item< enum Constants [private] from: FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift:60:0>
Item< var cancellable [private] from: FlowCrypt/Functionality/FilesManager/FilesManager.swift:35:0>
Item< func performGmailApiMigration [private] from: FlowCrypt/Functionality/Migration/DBMigrationService.swift:41:0>
Item< var logger [private lazy] from: FlowCrypt/Functionality/Services/Local Private Key Services/KeyDataStorage.swift:13:0>
Item< var cancellable [private] from: FlowCrypt/Functionality/Services/Backup Services/BackupService.swift:16:0>
Item< enum CodingKeys [private] from: FlowCrypt/Functionality/Services/Account Server Services/EnterpriseServerApi.swift:53:0>
Item< func url [private static] from: FlowCrypt/Functionality/Services/Account Server Services/BackendApi.swift:14:0>
 Item< func normalize [private static] from: FlowCrypt/Functionality/Services/Account Server Services/BackendApi.swift:18:0>
Item< let attester [private] from: FlowCrypt/Controllers/Settings/Backup/Backups Option Scene/BackupOptionsViewController.swift:34:0>
Item< var logger [private lazy] from: FlowCrypt/Controllers/Compose/ComposeViewController.swift:25:0>
 Item< var composedLatestDraft [private] from: FlowCrypt/Controllers/Compose/ComposeViewController.swift:67:0>
Item< var logger [private lazy] from: FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift:32:0>
Item< var logger [private lazy] from: FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift:38:0>
Item< func handleAnotherKeySelection [private] from: FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift:291:0>
Item< var logger [private lazy] from: FlowCrypt/Controllers/SignIn/SignInViewController.swift:31:0>
Item< func openDraft [private] from: FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:30:0>
```

**Comment by ivan-ushakov** [comment]
> what about unused code?

We could remove it too. @tomholub  what do you think? We could change name of the issue and PR or create new issue.

**Comment by tomholub** [comment]
I've filed a separate issue

**Pull request merged**
