### PR TITLE
#921 Recipients list improvements

### LINKED ISSUE #921: gmail conversation view - it's not clear to whom each message was sent
When message is unrolled, there should be a to: field. Also, check what Gmail does for rendering cc: and do the same.

-------

ios app

image

Gmail web app:

image

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR includes
- 'To: ..." field for expanded messages
- detailed view with "To: ...", "Cc: ...", "Bcc: ..." recipients
- updated labels for 'Sent' screen with list of all recipients

close #921

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated - added ui test for checking recipients list

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Thanks! Please also take some screenshots for reference.

**Comment by sosnovsky** [comment]
> Thanks! Please also take some screenshots for reference.

For sure, currently finishing some last fixes before sending to review

**Comment by sosnovsky** [comment]
Default collapsed state
Simulator Screen Shot - iPhone 12 - 2021-12-02 at 17 43 15

Expanded view after user tapped on recipients line
Simulator Screen Shot - iPhone 12 - 2021-12-02 at 17 43 20

**Comment by tomholub** [comment]
This is great.

**Review by tomholub — APPROVED** [review]

**Review by tomholub — DISMISSED** [review]

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
I'll update this to master

**Comment by tomholub** [comment]
No conflicts, miraculously

**Review by tomholub — APPROVED** [review]

**Pull request merged**
