### PR TITLE
#1171 Put db calls into a storage method

### LINKED ISSUE #1171: related db calls should be put into a storage method that has a tx
This should be made a transaction in storage (can be another PR later) else it produces inconsistent results.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1165#discussion_r762539199_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR put db calls into a storage method

close #1171 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@tomholub I couldn't find anywhere for such case.
So I only updated `removePubKey` function.

> applies to any place that we are doing more than one db write call within some method. Whether that is done in a loop or updating two tables etc.

**Comment by sosnovsky** [comment]
@ioanmo226 I found one more place with this case - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/App/AppStartup.swift#L58

**Comment by ioanmo226** [comment]
I also thought of that.

But I didn't change it because of following reasons.
1. It had `await` syntax in for loop and therefore we can't wrap for loop in storage.write.
2. That code should be removed after a few days/months.

**Comment by sosnovsky** [comment]
Ah, I see, then everything is good 👍

**Review by sosnovsky — APPROVED** [review]

**Pull request merged**
