### PR TITLE
#291 fix showspinner

### LINKED ISSUE #291: Fix showSpinner()
showSpinner() is an extension method to show MBProgressHUD on a view. 
Spinner dispatched on main queue with animation and without any completion on when animation ends. 
This can lead to a bug that HUD is not showed if any other operation scheduled

see `// TODO: - fix for spinner`

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed spinner and uses [ProgressHud](https://github.com/relatedcode/ProgressHUD/)

close #291 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
Yeah, I think it's expected behavior.
When we try to show side menu, we show spinner and then once load (fetching label list from api/cache)finishes we hide spinner.

**Comment by ioanmo226** [comment]
Maybe we should only show&hide spinner when `force` load flag is true?

**Comment by sosnovsky** [comment]
Ah, I just checked App Store build and it has spinner on side menu too, but because of quicker animation it's almost not visible. Can we change duration of animation of spinner appearance or maybe completely disable it for spinner in side menu?

> Maybe we should only show&hide spinner when force load flag is true?

Yes, let's show it only when `force` is true

**Review by sosnovsky — APPROVED** [review]
👍

**Pull request merged**
