### PR TITLE
Bugfix/issue 525 compose disappear

### LINKED ISSUE #525: compose content disappears on app blur
1) type text in compose view
2) put app into background
3) put app into foreground

actual result: composed message content disappears

expected result: composed message content should remain unchanged

tested with reply, probably problem in both

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR fixes content disappearing when sending app to background while on Compose mail screen.
Issue affected not only Message text, but Subject too. It occurred also when rotating phone from portrait to landscape and back.

close #525

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated - added UI test for checking compose screen data persistence.

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by tomholub — APPROVED** [review]
Thanks for the updated test! Looks good. I'll go ahead and test it manually too.

@Kharchevskyi if manual testing is successful, I'll merge it - later please see if you have any comments regarding code.

**Review by tomholub — CHANGES_REQUESTED** [review]
New message works well, but reply doesn't - try the following scenarios:

-----------

1) open encrypted message
2) tap reply
expected: the quoted text shows right away
actual: quoted text only appears once I start typing

-----------------

1) open encrypted message
2) tap reply
3) start typing your message
4) tap home and then come back
expected: text is exactly as I left it
actual: text is empty

**Comment by sosnovsky** [comment]
I tested first scenario - it's reproducible in `master` branch too, was caused by this change https://github.com/FlowCrypt/flowcrypt-ios/commit/c9788ca1ae718f8cc59d41f3a8188e54fafc54f0#diff-42fcab7325a0eb1205afe985324f4fd5e07f1e8add0ae0f759d92fa3c30787e4R342

**Comment by tomholub** [comment]
Our lacking tests are showing again. @fcvakintos will start working on improving our UI tests and having them run on CI (he's starting later this week). If you could please also update the tests to cover this case, that would be great.

**Comment by sosnovsky** [comment]
I fixed found issues and added ui test for checking reply text visibility.

**Comment by tomholub** [comment]
Thanks! Could you please try to tackle #516 next? If you get any leads/clues, even if incomplete, please add a comment there, which may help others. It's quite a crippling bug.

**Review by tomholub — APPROVED** [review]
I can confirm all of these work well now. Thanks again!

**Pull request merged**
