### PR TITLE
Add index-based accessibilityIds for recipient

### LINKED ISSUE #1197: index-based accessibilityIds for recipient bubbles/badges in compose
Ok, then we need updated accessibility identifiers to include the color for the recipient bubbles.

`to1orange` - first recipient has orange color (or `to1green` - first recipient has green color, etc)
`to2red` - second recipient has red color

And so on.

so its `"to" + index + color`, where color can be `gray|orange|red|green`

Once you have these, you will be checking that for example `to1gray` text contains `available.on@attester.test`

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/736#issuecomment-988832107_

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR adds index-based accessibilityIds for recipient

close #1197 
issue #1199 
----------------------------------

**Tests**:
- Does not need tests (refactor only, docs or internal changes)
--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by Kharchevskyi** [comment]
Screenshot 2021-12-12 at 15 29 51
Screenshot 2021-12-12 at 15 30 14

**Comment by Kharchevskyi** [comment]
@fcvakintos can you please check that this format of accessibility ids works for you in scope of this pr

**Comment by fcvakintos** [comment]
@Kharchevskyi can you add for grey recipient too?
@tomholub FYI^

**Comment by Kharchevskyi** [comment]
@fcvakintos should be there already. Have you checked?

**Comment by fcvakintos** [comment]
yes, but for Grey the new id is not displayed
Screenshot 2021-12-13 at 10 12 46

**Comment by Kharchevskyi** [comment]
Will check. Thanks

**Comment by tomholub** [comment]
If we are also setting a new format for accessibility ids, then let's have every accessibility id start with `aid-` to distinguish it from other methods to query elements. In appium, they are otherwise comingled.

**Comment by Kharchevskyi** [comment]
@fcvakintos thanks, now should be ok.

Screenshot 2021-12-13 at 16 45 00

**Review by tomholub — APPROVED** [review]

**Pull request merged**
