### PR TITLE
Message signed by unknown key should have a different badge

### LINKED ISSUE #1112: message signed by unknown key should have a different badge
This one is not right - signed only message that is missing pubkey should have encryption badge of `not encrypted` and a signature badge that says it cannot be verified due to missing pubkey.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1088#discussion_r758616826_

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #1112

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ivan-ushakov** [comment]
Simulator Screen Shot - iPhone 11 Pro - 2021-11-30 at 20 45 11

**Review by tomholub — APPROVED** [review]
excellent

**Comment by tomholub** [comment]
Please don't delete an email from e2e account until the PR that stops using it was merged. It breaks all other branches. 🤷 Thanks!

**Comment by ivan-ushakov** [comment]
> Please don't delete an email from e2e account until the PR that stops using it was merged. It breaks all other branches. 🤷 Thanks!

Oh, sorry for this.

**Comment by tomholub** [comment]
No worries - gets a while to get used to. Since the account is used as-is across PRs, then one has to follow sequence: 1) write code to stop using an email 2) get PR merged to master 3) wait until other PRs pull it 4) delete email from live account

Maybe next time, can file an issue to delete the email a month later, or something like that.

**Pull request merged**
