### PR TITLE
#1449 Use accessibility identifiers for all screens

### LINKED ISSUE #1199: format of accessibility ids
> Also for the future what are the requirements for accessibility id for you? 
> Does it matter if the id is capitalized/lowercased/camelized?

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/issues/1187#issuecomment-988924329_

Good question. I would actually most prefer a dash. And I would like to always prepend it with "aid" (differentiate from value content which is queried the same way) to become  `aid-menu-item-INBOX`

### LINKED ISSUE #1449: add accessibility ids
never use position based element queries, instead always use accessibility identifiers. Add them to codebase when missing.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1056#issuecomment-974681036_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR used accessibility identifiers for all screens

close #1449 // if this PR closes an issue
close #1199 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@tomholub How can I upload new flowcrypt app to aws?
We need to upload/use new flowcrypt.app  (for FlowcryptOld.app) after I complete this PR.

image

**Comment by tomholub** [comment]
If you can build it, then you can upload the zip here in a comment instead. Then use the uploaded link on semaphore.

**Comment by ioanmo226** [comment]
@tomholub Here's new FlowcryptOld.app zip file. Please let me know once you upload this file.

**Comment by tomholub** [comment]
Try drafting a release here https://github.com/FlowCrypt/flowcrypt-ios/releases/new

**Comment by ioanmo226** [comment]
ok

**Comment by tomholub** [comment]
It saves it from browser but not from terminal. I'll upload it to aws

**Comment by tomholub** [comment]
Ah, I see. I already uploaded it to AWS anyway. Here it is https://flowcrypt.s3.eu-central-1.amazonaws.com/release/flowcrypt-ios-old-version-for-ci-storage-compatibility-2022-05-09.zip

**Comment by ioanmo226** [comment]
@sosnovsky Please review

**Review by sosnovsky — APPROVED** [review]
Well done, I like updated selectors naming 👍

**Pull request merged**
