### PR TITLE
Update copyright notice everywhere + update template

### LINKED ISSUE #556: update copyright notice everywhere + update template
In all files, this (with any year):

```
//  Copyright © 2021 FlowCrypt Limited. All rights reserved.
```

Should read:

```
//  Copyright © 2017-present FlowCrypt a. s. All rights reserved.
```

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #556

----------------------------------

**Tests**
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ivan-ushakov** [comment]
@tomholub Do you need to update this also for TypeScript and JavaScript files?

**Comment by tomholub** [comment]
> @tomholub Do you need to update this also for TypeScript and JavaScript files?

Good question! Definitely, let's get it updated.

**Comment by ivan-ushakov** [comment]
Currently you have following variations.

```
/* © 2016-present FlowCrypt Limited. Limitations apply. Contact human@flowcrypt.com */
```

```
/* ©️ 2016 - present FlowCrypt a.s. Limitations apply. Contact human@flowcrypt.com */
```

How do you want to unify this?

**Comment by tomholub** [comment]
Let's do this in TypeScript:

```
2016 - present FlowCrypt a.s. Limitations apply. Contact human@flowcrypt.com
```

To make the TypeScript part consistent with browser extension codebase.

That means the TypeScript license header and the Swift one will differ a bit.

**Review by tomholub — APPROVED** [review]
Thanks!

**Pull request merged**
