### PR TITLE
#2523 Reply formatting fix

### LINKED ISSUE #2523: Old messages are merged into 1 line on reply
When replying old messages are merged into 1 line, which leads to incorrect thread rendering

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR fixes broken formatting for reply messages

before

after

close #2523

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
Hi @ioanmo226, can you please check this PR.
It should be the last one for 1.3.0 release, after it I'll prepare new build for App Store review

**Comment by ioanmo226** [comment]
Ok, sure

**Review by ioanmo226 — APPROVED** [review]
👍

**Comment by ioanmo226** [comment]
@sosnovsky Please merge this PR. I don't have permission.
Will ask Den about it.

**Pull request merged**
