### PR TITLE
Feature/issue 193 attachments list

### PR DESCRIPTION
**Pull request by qsoftdevelopment**
minor code refactoring

### CODE REVIEW

**Comment by tomholub** [comment]
Emir won't be continuing with us. @Kharchevskyi please have a look at resolving the conflicts when you have a chance. Thanks!

**Comment by Kharchevskyi** [comment]
Simulator Screen Shot - iPhone 8 - 2021-05-13 at 12 51 31

**Comment by Kharchevskyi** [comment]
@tomholub reworked functionality. 
* Removed Attachments node which was like a box for Attachment nodes. 
* Added second section to Message view controller where number of rows are equal to number of attachments.
* Removed logical part from view controller to service

**Review by tomholub — APPROVED** [review]
Thanks!

**Pull request merged**
