### PR TITLE
provide app icons in various sizes

### LINKED ISSUE #502: Add app current configuration label
agree - let's make a separate issue for the future

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/272#issuecomment-920075675_

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #502

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ivan-ushakov** [comment]
Now only standard icon fixed for 3x.

**Comment by tomholub** [comment]
The PR changelog has many unrelated changes - have a look.

**Review by tomholub — APPROVED** [review]
Approve but doesn't address the issue yet, therefore should not #close it @ivan-ushakov

**Comment by tomholub** [comment]
> close #502

This should be updated to `issue #502` when it doesn't fully address the issue yet

**Pull request merged**
