### PR TITLE
add swiftlint and swfitformat

### PR DESCRIPTION
**Pull request by Kharchevskyi**
https://github.com/realm/SwiftLint
https://github.com/nicklockwood/SwiftFormat

SwiftLint and SwiftFormat are tools to lint and autocorrect swift code.
This tools allows autocorrecting swift files automatically.
Also, add them as a prebuild phase to autocorrect files every time you build the project

### CODE REVIEW

**Comment by Kharchevskyi** [comment]
In this PR there are few rules which is added automatically, like

- Files should not contain leading whitespace. https://realm.github.io/SwiftLint/leading_whitespace.html
- line_length to avoid lines more then 140 characters
- force try rule
and a few others.

All other rules will be added one by one in separate PRs.

To add a new rule - just add it to `.swiftlint.yml` file. https://realm.github.io/SwiftLint/
To add autoformatting - just update `Scripts/format.sh` file. https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md

**Comment by Kharchevskyi** [comment]
close #233

**Comment by tomholub** [comment]
Please have a look at the tests here too. Thanks!

**Comment by Kharchevskyi** [comment]
> Please have a look at the tests here too. Thanks!

I did some fixes to run on Xcode 11.3.1 instead of 11.4 (which Semaphore CI is using). 
Please check https://github.com/FlowCrypt/flowcrypt-ios/pull/231. This PR should be merged first to fix tests.

**Comment by tomholub** [comment]
Got it, merged! Once conflicts are resolved, can merge this too.

**Comment by Kharchevskyi** [comment]
> Got it, merged! Once conflicts are resolved, can merge this too.

It's better to merge this pr after #226 and #229 to avoid conflicts.

**Comment by Kharchevskyi** [comment]
This PR contains only formatting changes made with SwiftFormat. 
SwiftFormat runs as a prebuild phase. It will automatically format files

**Pull request merged**
