### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR updates project dependencies
- Specify ruby version to be `2.5.1`, which is currently used on CI. 
https://docs.semaphoreci.com/ci-cd-environment/macos-xcode-12-image/
- Updates make file
- Updates Readme
- Updates bundler version to `2.2.25`
----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes) 

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by Kharchevskyi** [comment]
@tomholub it looks that `fastlane` plugin `semaphore` is not compatible with latest version of a fastlane. 
please check `1837763`(with plugin) and `b2032d4`(`setup_semaphore` is commented out). (also see #421)

What this plugin is responsible for?

**Comment by tomholub** [comment]
> What this plugin is responsible for?

I don't know, I don't remember adding it.

**Comment by Kharchevskyi** [comment]
@tomholub FlowCryptTests(with email server) - are failing. Can you please check?

**Review by tomholub — APPROVED** [review]
I can run these setup commands successfully

**Comment by tomholub** [comment]
I'll merge this for now, and try the tests PR again.

**Pull request merged**
