### PR TITLE
issue #583 add StorageMethod enum

### LINKED ISSUE #583: use enum for StorageMethod
instead of these `shouldStorePassPhrase` and `inStorage` and similar booleans, we should use an enum like `StorageMethod.permanent` vs `StorageMethod.memory`, everywhere. That would be for another PR. Then here it will say `if storageMethod == StorageMethod.memory`

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/577#discussion_r719542689_

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR replaces boolean values for passphrases storage with `StorageMethod` enum

close #583

----------------------------------

**Tests**:
- Tests added or updated - updated `PassPhraseStorageTests` to use new `storageMethod` param

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by tomholub — APPROVED** [review]
Looks good!

**Comment by sosnovsky** [comment]
@tomholub new builds are failing on semaphore with such error log
```
fatal: Unable to read current working directory: No such file or directory
fatal: fetch-pack: invalid index-pack output
bash: cd: /Users/semaphore/git/flowcrypt-ios: No such file or directory
```

Do you know possible reason? Maybe some configs were changed?

**Comment by Kharchevskyi** [comment]
@tomholub @sosnovsky it looks that job for `TypeScript - Core standalone tests` are not configured properly. 
Checkout operation performs twice, once inside prologue 
```
prologue:
        commands:
          - checkout
```
and second time in lane
```
- name: TypeScript - Core standalone tests
          commands:
            - sem-version node 12
            - checkout
```
Are there any reasons to do this twice?
Screenshot 2021-10-05 at 22 26 18

**Comment by tomholub** [comment]
I don't think there is any reason for doing it twice, checkout in prologue should be enough.

**Comment by tomholub** [comment]
@Kharchevskyi thank you - that was it! 👍

**Review by tomholub — APPROVED** [review]

**Pull request merged**
