### PR TITLE
Reenable swift format. Changes in swiftlint rules

### LINKED ISSUE #1121: disable type_name style lint
> Type Name Violation: Type name should be between 3 and 40 characters long: 'SetupManuallyEnterPassPhraseViewController' (type_name)

not a meaningful lint, long names sometimes bring more clarity

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR reenables formatting with SwiftFormat
* Added SwiftFormat as Package _(check BuildTools)_
* Added configuration file to each target `.swiftformat `
* Reenable existed formating rules
* Disable `type_name` swift lint rule
* Added format build phase

close #1121

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by Kharchevskyi** [comment]
@sosnovsky may I ask you to checkout pull this branch and try to run this branch locally. 
Also can you please verify it works on your machine?
(You can just for example add  few new lines in some file and build the app. SwiftFormat should remove them during build phase)

**Comment by sosnovsky** [comment]
@Kharchevskyi `swiftformat` works for me now - empty lines were deleted during building 👍

**Review by sosnovsky — COMMENTED** [review]
It works well, but there is an issue with files overwrite (as mentioned here https://github.com/nicklockwood/SwiftFormat#xcode-build-phase) - undo history for files is removed on each build.

As a possible solution we can run `swiftformat` only when building app for unit tests. It happens less often and shouldn't affect development process.

**Comment by Kharchevskyi** [comment]
Tbh, haven't got any issues with that. 
Let's maybe fill another issue for that and if it would bother someone will move it to unit test phase

**Comment by Kharchevskyi** [comment]
Created a draft PR for that 
https://github.com/FlowCrypt/flowcrypt-ios/pull/1341
Let's see if there going to be any problems with history overwriting.
If you would face any issues with that we can just merge above mentioned PR. 
I would suggest to try to keep this implementation because during development you not always build tests

**Review by sosnovsky — APPROVED** [review]
Agree, let's try it this way for now ✅

**Pull request merged**
