### PR TITLE
iPad text insets

### LINKED ISSUE #1270: iPad - Text insets
Fix insets for iPad. Insets should be at least 24 point

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR fixes text insets for iPad
close #1270

- [x] InboxViewController
- [x] SearchViewController
- [x] ThreadDetailsViewController
- [x] ThreadDetailsViewController + attachment
- [x] ComposeViewController
- [x] MyMenuViewController
- [x] SettingsViewController
- [x] ContactDetailViewController
- [x] ContactsListViewController
- [x] ContactKeyDetailViewController
- [x] KeyDetailInfoViewController
- [x] KeySettingsViewController
- [x] PublicKeyDetailViewController
- [x] BackupViewController
- [x] BackupOptionsViewController
- [x] LegalViewController
----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by Kharchevskyi** [comment]
MyMenuViewController
ComposeViewController-contacts
ComposeViewController-no-contacts
ComposeViewController

**Comment by Kharchevskyi** [comment]
ContactDetailViewController
ContactsListViewController
SettingsViewController
ContactKeyDetailViewController
KeyDetailInfoViewController
KeySettingsViewController
PublicKeyDetailViewController

**Review by sosnovsky — APPROVED** [review]
iPad version looks much better now 👍

**Pull request merged**
