### PR TITLE
update core js - keyCacheWipe, key_mismatch fix, plainAtt data

### PR DESCRIPTION
**Pull request by tomholub**
This PR updates core functionality by adding a keyCacheWipe endpoint (useful when wiping pass phrase which was kept in memory) and ensuring that a mismatched message keys properly reports key_mismatch error even when missing a pass phrase.

Also `plainAtt` blocks are no longer filtered out of the response, so that they can be rendered / their content is can be downloaded for #194 

issue #197 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests updated here https://github.com/FlowCrypt/flowcrypt-mobile-core/pull/157

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
discussion at https://github.com/FlowCrypt/flowcrypt-android/issues/1251#issuecomment-854482750

**Comment by tomholub** [comment]
@ekievsky or @Kharchevskyi please have a look that the app still works as expected and if so, approve or add comments. Thanks!

**Comment by Kharchevskyi** [comment]
Tested on `update-core` branch and also by pulling in `feature/issue-197-pass-phrase-memory`. Functionality works fine

**Comment by tomholub** [comment]
@Kharchevskyi then you can go to `Files changed` -> `Review changes` -> `Approve` and that will merge the PR. Thanks!

**Review by ekievsky — APPROVED** [review]

**Pull request merged**
