### PR TITLE
#2095 fix: forward message issue for email with attached pub key

### LINKED ISSUE #2095: Can't forward message with attached public key
Steps to reproduce:
1. compose encrypted email in browser extension and click `Include your public key` button in the bottom right corner of compose box
2. send this message with attached pubkey
3. open message in iOS app and try to forward it
4. app shows error message `Error during parsing. This message / key probably does not conform to a valid OpenPGP format.`

Issue appeared in 1.2.2, worked well in 1.2.1

UI test should also be added for this case

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed forward message issue for email with attached pub key

close #2095 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@sosnovsky In Semaphoreci, the test 'check forward message with attached pub key' fails strangely. Could you please check on your local side to see if you can reproduce this issue?

**Comment by sosnovsky** [comment]
> @sosnovsky In Semaphoreci, the test 'check forward message with attached pub key' fails strangely. Could you please check on your local side to see if you can reproduce this issue?

Test passes well locally for me, I tried to update appium on semaphore ci

**Comment by sosnovsky** [comment]
semaphore should also take screenshot of failed test, which then stored in the `Artifacts`, but currently there is nothing there. probably need also check why screenshot isn't created, as it should help to find why test fails

**Comment by ioanmo226** [comment]
Yeah, also now all tests fail in both local & semaphoreci. not sure why it is happening. i tried to revert package updates but still same.
Digging deeper now

**Comment by ioanmo226** [comment]
Fixed. Also fixed image not saving issue when tests failed.
Please check.

**Review by sosnovsky — APPROVED** [review]
Well done 👍

**Review by sosnovsky — APPROVED** [review]

**Pull request merged**
