### PR TITLE
#1453 Focus textfield for reply/forward

### LINKED ISSUE #1453: after reply, message should be in focus
when I open a message and tap reply, currently I will end up in focus (caret), which then gets collapsed (correctly). But in this situation, caret should be on the beginning of the reply message I'm composing.

This is different from forward - for forward, it's correct that the recipient is in focus. (and recipients not in collapsed view)

Please add a test for it - for any of the tests that tap reply, verify where the caret is. Similarly for forward.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR focuses textfield for reply/forward in ComposeView

close #1453 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by tomholub — APPROVED** [review]
Looks good. Please later investigate the failing test.

I wonder if we are going over the configured semaphore run limit for each CI run.

**Comment by ioanmo226** [comment]
@tomholub I think so because tests run successfully in my local.

**Comment by tomholub** [comment]
Let's see. Sometime in the future, we'll split the ui tests up to run on two machines, and take less time that way.

**Comment by ioanmo226** [comment]
OK

**Comment by ioanmo226** [comment]
@tomholub I'm stuck with testing because there seems no way to check if element is focused or not in Appium.
I'm finding hacky way now.

**Review by tomholub — APPROVED** [review]

**Pull request merged**
